apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: customer-success-fte

resources:
- namespace.yaml
- configmap.yaml
- secrets.yaml
- serviceaccount.yaml
- service.yaml
- deployment-api.yaml
- deployment-worker.yaml
- deployment-frontend.yaml
- deployment-agent.yaml
- hpa.yaml
- ingress.yaml
- kafka/pvc.yaml
- kafka/zookeeper-statefulset.yaml
- kafka/kafka-statefulset.yaml

commonLabels:
  app.kubernetes.io/name: novasaas
  app.kubernetes.io/managed-by: kustomize
